// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type Champion struct {
	ID    string
	Name  sql.NullString
	Image sql.NullString
	Tags  sql.NullString
}

type Setting struct {
	Key   string
	Value sql.NullString
}

type Skin struct {
	ID       int64
	Name     string
	FilePath string
	IsActive sql.NullInt64
}

type SkinChampion struct {
	SkinID     int64
	ChampionID string
}
