// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteSetting = `-- name: DeleteSetting :exec
DELETE FROM settings WHERE key = ?1
`

func (q *Queries) DeleteSetting(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteSetting, key)
	return err
}

const deleteSkinById = `-- name: DeleteSkinById :exec
DELETE FROM skins WHERE id = ?
`

func (q *Queries) DeleteSkinById(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSkinById, id)
	return err
}

const deleteSkinChampionsBySkinId = `-- name: DeleteSkinChampionsBySkinId :exec
DELETE FROM skin_champions WHERE skin_id = ?
`

func (q *Queries) DeleteSkinChampionsBySkinId(ctx context.Context, skinID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSkinChampionsBySkinId, skinID)
	return err
}

const fetchSkinsForChampionById = `-- name: FetchSkinsForChampionById :many
SELECT skins.id, skins.name, skins.file_path, skins.is_active
FROM skins
INNER JOIN skin_champions ON skins.id = skin_champions.skin_id
WHERE skin_champions.champion_id = ?1
`

func (q *Queries) FetchSkinsForChampionById(ctx context.Context, id string) ([]Skin, error) {
	rows, err := q.db.QueryContext(ctx, fetchSkinsForChampionById, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skin
	for rows.Next() {
		var i Skin
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FilePath,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM settings WHERE key = ?1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value sql.NullString
	err := row.Scan(&value)
	return value, err
}

const insertOrUpdateChampion = `-- name: InsertOrUpdateChampion :exec
INSERT INTO champions(id, name, image, tags) 
VALUES (?, ?, ?, ?)
ON CONFLICT(id)
DO UPDATE SET 
    name = sqlc.arg(updateName),
    image = sqlc.arg(updateImage),
    tags = sqlc.arg(updateTags)
`

type InsertOrUpdateChampionParams struct {
	ID    string
	Name  sql.NullString
	Image sql.NullString
	Tags  sql.NullString
}

func (q *Queries) InsertOrUpdateChampion(ctx context.Context, arg InsertOrUpdateChampionParams) error {
	_, err := q.db.ExecContext(ctx, insertOrUpdateChampion,
		arg.ID,
		arg.Name,
		arg.Image,
		arg.Tags,
	)
	return err
}

const insertSkin = `-- name: InsertSkin :one
INSERT OR IGNORE INTO skins (name, file_path) 
VALUES (?1, ?2)
RETURNING id
`

type InsertSkinParams struct {
	Name     string
	FilePath string
}

func (q *Queries) InsertSkin(ctx context.Context, arg InsertSkinParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertSkin, arg.Name, arg.FilePath)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const linkSkinToChampions = `-- name: LinkSkinToChampions :exec
INSERT OR IGNORE INTO skin_champions(skin_id, champion_id) 
VALUES (?, ?)
`

type LinkSkinToChampionsParams struct {
	SkinID     int64
	ChampionID string
}

func (q *Queries) LinkSkinToChampions(ctx context.Context, arg LinkSkinToChampionsParams) error {
	_, err := q.db.ExecContext(ctx, linkSkinToChampions, arg.SkinID, arg.ChampionID)
	return err
}

const selectActiveSkinNames = `-- name: SelectActiveSkinNames :many
SELECT name FROM skins WHERE is_active = 1
`

func (q *Queries) SelectActiveSkinNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, selectActiveSkinNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectChampions = `-- name: SelectChampions :many
SELECT id, name, image, tags 
FROM champions
`

func (q *Queries) SelectChampions(ctx context.Context) ([]Champion, error) {
	rows, err := q.db.QueryContext(ctx, selectChampions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Champion
	for rows.Next() {
		var i Champion
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectChampionsBySkinId = `-- name: SelectChampionsBySkinId :many
SELECT c.id, c.name, c.image, c.tags
FROM champions c
INNER JOIN skin_champions sc ON c.id = sc.champion_id
WHERE sc.skin_id = ?1
`

func (q *Queries) SelectChampionsBySkinId(ctx context.Context, skinid int64) ([]Champion, error) {
	rows, err := q.db.QueryContext(ctx, selectChampionsBySkinId, skinid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Champion
	for rows.Next() {
		var i Champion
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectChampionsCount = `-- name: SelectChampionsCount :one
SELECT COUNT(*) FROM champions
`

func (q *Queries) SelectChampionsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, selectChampionsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const selectSkinFilePathById = `-- name: SelectSkinFilePathById :one
SELECT file_path FROM skins WHERE id = ?
`

func (q *Queries) SelectSkinFilePathById(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, selectSkinFilePathById, id)
	var file_path string
	err := row.Scan(&file_path)
	return file_path, err
}

const setSetting = `-- name: SetSetting :exec
INSERT INTO settings (key, value) 
VALUES (?, ?) 
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type SetSettingParams struct {
	Key   string
	Value sql.NullString
}

func (q *Queries) SetSetting(ctx context.Context, arg SetSettingParams) error {
	_, err := q.db.ExecContext(ctx, setSetting, arg.Key, arg.Value)
	return err
}

const updateSkinActive = `-- name: UpdateSkinActive :exec
UPDATE skins SET is_active = ?1 WHERE name = ?2
`

type UpdateSkinActiveParams struct {
	Active sql.NullInt64
	Name   string
}

func (q *Queries) UpdateSkinActive(ctx context.Context, arg UpdateSkinActiveParams) error {
	_, err := q.db.ExecContext(ctx, updateSkinActive, arg.Active, arg.Name)
	return err
}
