// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadSkin(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadSkin'](arg1, arg2, arg3);
}

export function GetChampions() {
  return window['go']['main']['App']['GetChampions']();
}

export function GetGalleryForSkin(arg1) {
  return window['go']['main']['App']['GetGalleryForSkin'](arg1);
}

export function GetSkinDetails(arg1) {
  return window['go']['main']['App']['GetSkinDetails'](arg1);
}

export function GetSkins() {
  return window['go']['main']['App']['GetSkins']();
}
