// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function BrowseLeagueFolder():Promise<string>;

export function DeleteSkin(arg1:string):Promise<void>;

export function DisableSkin(arg1:string):Promise<void>;

export function DownloadSkin(arg1:string,arg2:string,arg3:Array<db.Champion>,arg4:string):Promise<void>;

export function EnableSkin(arg1:string):Promise<void>;

export function FetchSkinsForChampionById(arg1:string):Promise<Array<db.DownloadedSkin>>;

export function FindLeaugeDownload():Promise<string>;

export function GetChampions():Promise<Array<db.Champion>>;

export function GetChampionsForSkin(arg1:string):Promise<Array<db.Champion>>;

export function GetGalleryForSkin(arg1:string):Promise<Array<db.Gallery>>;

export function GetSetting(arg1:string):Promise<string>;

export function GetSkinDetails(arg1:string):Promise<db.Skin>;

export function GetSkins(arg1:string,arg2:number):Promise<db.SkinsPage>;

export function OpenDirectoryDialog(arg1:string,arg2:Array<string>):Promise<string>;

export function OpenMultipleFilesDialog(arg1:string,arg2:Array<string>):Promise<Array<string>>;

export function RunCSLOLInjector():Promise<void>;

export function RunPatcher(arg1:Array<string>):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;
