// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseLeagueFolder() {
  return window['go']['main']['App']['BrowseLeagueFolder']();
}

export function DisableSkin(arg1) {
  return window['go']['main']['App']['DisableSkin'](arg1);
}

export function DownloadSkin(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DownloadSkin'](arg1, arg2, arg3, arg4);
}

export function EnableSkin(arg1) {
  return window['go']['main']['App']['EnableSkin'](arg1);
}

export function FetchSkinsForChampionById(arg1) {
  return window['go']['main']['App']['FetchSkinsForChampionById'](arg1);
}

export function FindLeaugeDownload() {
  return window['go']['main']['App']['FindLeaugeDownload']();
}

export function GetChampions() {
  return window['go']['main']['App']['GetChampions']();
}

export function GetGalleryForSkin(arg1) {
  return window['go']['main']['App']['GetGalleryForSkin'](arg1);
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function GetSkinDetails(arg1) {
  return window['go']['main']['App']['GetSkinDetails'](arg1);
}

export function GetSkins(arg1, arg2) {
  return window['go']['main']['App']['GetSkins'](arg1, arg2);
}

export function OpenDirectoryDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1, arg2);
}

export function OpenMultipleFilesDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenMultipleFilesDialog'](arg1, arg2);
}

export function RunCSLOLInjector() {
  return window['go']['main']['App']['RunCSLOLInjector']();
}

export function RunPatcher(arg1) {
  return window['go']['main']['App']['RunPatcher'](arg1);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}
