// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function DisableSkin(arg1:string):Promise<void>;

export function DownloadSkin(arg1:string,arg2:string,arg3:Array<db.Champion>,arg4:string):Promise<void>;

export function EnableSkin(arg1:string):Promise<void>;

export function FetchSkinsForChampionById(arg1:string):Promise<Array<db.DownloadedSkin>>;

export function FindLeaugeDownload():Promise<string>;

export function GetChampions():Promise<Array<db.Champion>>;

export function GetGalleryForSkin(arg1:string):Promise<Array<db.Gallery>>;

export function GetSetting(arg1:string):Promise<string>;

export function GetSkinDetails(arg1:string):Promise<db.Skin>;

export function GetSkins():Promise<Array<db.Skins>>;

export function SetSetting(arg1:string,arg2:string):Promise<void>;
