// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function DownloadSkin(arg1:string,arg2:string,arg3:Array<db.Champion>):Promise<void>;

export function GetChampions():Promise<Array<db.Champion>>;

export function GetGalleryForSkin(arg1:string):Promise<Array<db.Gallery>>;

export function GetSkinDetails(arg1:string):Promise<db.Skin>;

export function GetSkins():Promise<Array<db.Skins>>;
